<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$Isenable = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('productslider/general/enable');
$random = md5(uniqid(rand(), true));
if($Isenable) {
?>
	<div class="ivory_productslider slider_<?php echo $random; ?>">
		<?php if($block->getTitle()) { ?>
			<div class="block-title">
				<h2><?php echo $block->getTitle(); ?></h2>
			</div>
		<?php } ?>
		
		<?php
		$productCollection = $block->getProductCollection();
		if(!empty($productCollection->getData()) && count($productCollection->getData()) > 0)
		{
		?>
			<div class="wrapper grid products-grid">
				<ol class="list items product-items owl-carousel owl-theme">
					<?php
					
					foreach ($productCollection as $product) 
					{
						$imageType = 'product_base_image';
						$image = $block->getImage($product, $imageType);
					?>
						<li class="item product product-item">                        
							<div class="product-item-info">
								<a href="<?php echo $product->getProductUrl(); ?>" class="product-item-photo">
									<span class="product-image-container" style="width:240px;">
										<span class="product-image-wrapper" style="padding-bottom: 125%;">
											<img class="product-image-photo" src="<?php echo $image->getImageUrl(); ?>" alt="<?php echo $product->getName(); ?>">
										</span>
									</span>
								</a>
								<div class="product-item-details">
									<strong class="product-item-name">
										<a title="new product" href="<?php echo $product->getProductUrl(); ?>" class="product-item-link"><?php echo $product->getName(); ?></a>
									</strong>
									
									<?= /* @escapeNotVerified */ $block->getProductPrice($product); ?>

									<div class="product-item-actions">
										<div class="actions-primary">
											<?php if ($product->isSaleable()): ?>
													<button class="action tocart primary" data-post='<?php echo json_encode($block->getAddToCartPostParams($product)); ?>' type="button" title="Add to Cart">
														<span>Add to Cart</span>
													</button>
											<?php else: ?>
												<?php if ($product->isAvailable()): ?>
													<div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
												<?php else: ?>
													<div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
												<?php endif; ?>
											<?php endif; ?>
										</div>
										<div class="actions-secondary" data-role="add-to-links">
											<a href="#" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($product) ?>' class="action towishlist" data-action="add-to-wishlist" title="Add to Wish List">
												<span>Add to Wish List</span>
											</a>
											<a href="#" class="action tocompare" data-post='<?php  echo $this->helper('Magento\Catalog\Helper\Product\Compare')->getPostDataParams($product) ?>' title="Add to Compare">
												<span>Add to Compare</span>
											</a>
										</div>
									</div>
								</div>
							</div>
						</li> 
					<?php
					}
					?>
				</ol>
			</div>
			<script>
			require(['jquery','owl_carousel'], function($){
				$(function () { // to ensure that code evaluates on page load
					$('.slider_<?php echo $random; ?> .product-items').owlCarousel({
						// loop:true,
						nav:true,
						dots:false,
						margin:20,
						responsive:{
							0:{
								items:<?php echo ($block->getMobileCount())? $block->getMobileCount() : 1 ?>
							},
							600:{
								items:<?php echo ($block->getTabletCount())? $block->getTabletCount() : 3 ?>
							},
							1000:{
								items:<?php echo ($block->getDesktopCount())? $block->getDesktopCount() : 5 ?>
							}
						}
					});
				});
			});
			</script>
		<?php
		} else {
		?>
			<div class="opc-block-summary">Couldn't find any product.</div>
		<?php 	
		}
		?>
	</div>
<?php
}
?>